maticnetwork/heimdall

checkpoint/genesis.go, types/header.go
This to ensure that `CheckpointIndex` is not corrupted while import/export.
=> sorted headers before export+import

docker/Dockerfile.CS1001
This PR includes
Docker image for Counter Stage-0. Commit-id and config files are added in Dockerfile.
To run node, user just has to 
1. run the container.
2. update API_KEY, persistent_peers
3. start heimdall, rest-server
=> Dockerfile for CS1001

helper/toml.go
Default poll interval is not set for clerk and span service as respective config missing in toml.go.
=> fix poll interval issue

checkpoint/handler.go, checkpoint/types/merkel.go
Issue - https://github.com/maticnetwork/heimdall/issues/154
Currently, if blocks are not found we validate the transaction with the blocks found, instead of throwing Roothash doesnt match error we should throw blocks not found error.
=> MAT-677 - Handle block not found

helper/util.go
`GetVote` was using the first vote instead of first non-empty vote.
=> Fix: use first non-empty vote

app/app.go, checkpoint/client/cli/flags.go, checkpoint/client/cli/tx.go, checkpoint/module.go, checkpoint/querier.go, checkpoint/types/querier.go, staking/querier.go
Fixes #266 
- Adds a new flag --auto-configure for checkpoint module: This creates the next checkpoint based on the current state of the node and broadcasts it. 
Example command:
```
$ heimdallcli tx checkpoint send-checkpoint --auto-configure=true --chain-id=heimdall-ODAMAV
```
Unfortunately, I had to pass staking keeper to the querier for this one.
=> Adds --auto-configure for checkpoint

cmd/heimdalld/main.go
func InitializeNodeValidatorFiles was returning nil instead of err in a few cases.
=> MAT-1189: bug: return err instead of nil for init validator

bor/keeper.go, bor/side_handler.go, clerk/side_handler.go, staking/side_handler.go, topup/side_handler.go
**Problem Statement**
With Side-channel, as msg validations are done in `handler` and state update is done in `side_handler`, same msg  replayed multiple times will pass validations  in handler and updates state in side_handler.
**Solution**
Check in side_handler if msg is already processed before state update. 
1. Staking — check sequence
2. Bor — check if new span is there with id
3. Clerk — check if record is there with id
4. Topup — check sequence
=> MAT-1354 - Side-channel replay attack

bridge/setu/listener/maticchain.go, bridge/setu/listener/rootchain.go, bridge/setu/processor/checkpoint.go, chainmanager/querier_test.go, chainmanager/simulation/genesis.go, chainmanager/simulation/params.go, chainmanager/types/params.go, checkpoint/client/cli/tx.go, clerk/querier.go, clerk/side_handler.go, common/error.go, helper/call.go, helper/config.go, helper/mocks/IContractCaller.go, staking/client/cli/tx.go, staking/handler_test.go, staking/querier.go, staking/querier_test.go, staking/side_handler.go, topup/handler_test.go, topup/querier.go, topup/querier_test.go, topup/side_handler.go
Use confirmation blocks instead of confirmation time
This PR has fixes for
- https://linear.app/issue/MAT-1132/use-confirmation-blocks-instead-of-confirmation-time
- https://linear.app/issue/MAT-1305/10-bor-blocks-as-confirmation-for-checkpoint
=> MAT-1132 - Sidechannel confirmations

app/app.go
These params can be configured from `genesis.json` at
```js
"genesis_time": "2020-03-12T09:23:23.318713Z",
"chain_id": "heimdall-P5rXwg",
"consensus_params": {
"block": {
"max_bytes": "22020096",
"max_gas": "50000000",
"time_iota_ms": "1000"
},
"evidence": {
"max_age": "100000"
},
"validator": {
"pub_key_types": [
"secp256k1"
]
}
}
```
=> chg: remove hard coded consensus params

bridge/cmd/start.go, bridge/setu/listener/maticchain.go, bridge/setu/processor/base.go, bridge/setu/processor/checkpoint.go, bridge/setu/processor/clerk.go, bridge/setu/processor/fee.go, bridge/setu/processor/service.go, bridge/setu/processor/span.go, bridge/setu/processor/staking.go, bridge/setu/util/common.go, bridge/setu/util/paramscontext.go
This PR contains following bridge optimisations
```
MAT-1696 - Multiple span transactions for same spanID
Solution
- Add delay between each proposer.
```
```
MAT-1673 - Retry `tx` from bridge if failed during side-tx-processing
Solution
- After broadcasting transaction from bridge, add back the msg to queue with retry delay.
`return tasks.NewErrRetryTaskLater("some error", 6 * estimatedNextBlockTime)`
- After `6 blocks` produced on heimdall, same msg will be retried by bridge.
- As we validate and check if msg has been already processed or not on heimdall using `sequenceNo`,
- if already processed, bridge will ignore
- else, bridge will send the msg again repeating the process.
```
```
MAT-1228 - Add context params to cache to reduce params api call
Solution
- Cache the params and  reload …
```
=> MAT-1477 - Bridge optimizations

cmd/heimdalld/cmd/root.go, go.mod
1. show-account
2. show-privatekey
3. export-heimdall
4. generate-keystore
5. generate-validatorkey
6. address-to-hex
7. hex-to-address
=> Adding missing cmd to heimdall 

helper/call.go
- Earlier while validating checkpoint the heimdall used to check for latest block and compare if the end block for a checkpoint is lower than the latest number.
- In case of 0 block issue the latest number comes out to be 0 and hence the block check used to fail and checkpoint doesn't pass
- Now it will check if the end block is present or not instead of latest which used to give 0 block in case of 0 block issue.
=> Fix checkpoint issue when bor is in 0 block issue

README.md, bridge/bridge.go, bridge/cmd/root.go, bridge/setu/broadcaster/broadcaster_test.go, cmd/heimdallcli/main.go, cmd/heimdalld/main.go, helper/call_test.go, helper/config.go, helper/config_test.go, server/root.go
Right now, there are three Heimdall services that we have to run in the network:
- Daemon
- Bridge
- Rest server 
Rest server is defined in the Daemon binary and runs as:
```bash
$ heimdalld rest-server
```
However, the Bridge is an independent binary.
This makes it complex to distribute the software (release binaries and docker images).
The goal of this issue is to integrate the bridge on the Daemon alongside the Rest server in a command like this:
```bash
$ heimdalld bridge
```
=> POS-24 Embed Heimdall bridge in the Daemon binary

helper/config.go
Thanks to viper we can setup the automatic env configuration, this is very convenient for running in docker as we don't need to add explicit params to the CLI and we avoid having to sed on config files.
=> Allow Heimdall to be configured using env vars

Dockerfile, docker-compose.yml, docker/entrypoint.sh
With this PR we move towards the Docker philosophy of running just a single process. Running multiple processes without attending signals was not useful and dangerous for graceful stops.
- Refactor a bit the entrypoint so it responds to all binaries, heimdalld and bridge.
- Create a canonical docker-compose file to run all 3 components configuring them using env vars.
- heimdalcli could be run by overriding the entrypoint.
- Remove tini as now the main bin is heimdalld and it correctly handle signals.
Precede #748
=> Run with docker-compose

bridge/cmd/start.go, bridge/setu/util/common.go, cmd/heimdalld/main.go, helper/config.go, server/root.go
- added two flags --rest-server and --bridge for starting services alongside Heimdall daemon
- heimdall start command moved from Tendermint SDK to Heimdall in order to be able to modify it more freely
- added rest server and bridge async start ordering logic using channels
- added health check for rest server using open port check (for service ordering purposes)
- added default log level for bridge in order to bypass a Tendermint SDK function panic when no log level has been passed from flags and level is read from config.toml
Order of services graceful shutting down is yet to come.
=> POS-50: Run Rest and Bridge service alongside the Heimdall daemon.

.github/workflows/ci.yml, README.md, cmd/heimdalld/init.go, cmd/heimdalld/main.go, go.mod, helper/allocs/mainnet.json, helper/allocs/mumbai.json, helper/config.go, helper/genesis_file.go, sidechannel/keeper_test.go
We advise to users to use our Ansible scripts to deploy the Bor and Heimdall nodes using this playbook:
https://github.com/maticnetwork/node-ansible
There is a step in this process that runs a setup script for Heimdall to:
start the destination folder with $ heimdalld init
copy the cosmos genesis file to the folder, it is only available in the launch repo.
https://github.com/maticnetwork/node-ansible/blob/b7ab3f8078efd4a7337085fc68f672096f550708/roles/setup-network/tasks/setup.yml#L17
Unless this process is done, Heimdall cannot start.
The goal of this issue is to remove the need for this setup step.
Proposal
Move the code from the init command to its own function.
https://github.com/maticnetwork/heimdall/blob/master/cmd/heimdalld/init.go#L35
On starting the daemon, check if you need to …
=> POS-53 Remove setup script for Heimdall and embed genesis files

bridge/bridge.go, bridge/cmd/root.go, bridge/cmd/start.go, cmd/heimdalld/main.go, server/root.go
- Graceful shutdown of Heimdall, REST, and Bridge are all initiated by the same context signaled by the OS on interrupt and program termination
- Necessary code duplications are due to the private functions and types from Cosmos SDK that needed changes to accommodate shutdowns
=> POS-86: Graceful shutdown of Heimdall deamon, REST and Bridge

bridge/bridge.go, bridge/cmd/root.go, cmd/heimdallcli/main.go, cmd/heimdalld/main.go, helper/config.go
Implementation:
A new function has been added to helper/config.go:  "func DecorateWithHeimdallFlags".
The function takes a command and adds Heimdall flags into the command and simultaneously binds the flags to the viper.
One of the flags (added by the function) defines a new file which overrides  the standard configuration file.
The function ("func DecorateWithHeimdallFlags") is called for all commands that use "func InitHeimdallConfig" during initialization: heimdalld-rootCmd, bridge-rootCmd, heimdallCli-rootCmd. That way all commands that use Heimdall config structure can utilize flags.
IMPORTANT!
1. Initialization of Heimdall config structure has been changed. In other words "func InitHeimdallConfig" has been changed. Up until this task if a flag that defines a new configuration file …
=> POS-17: Add Heimdall flags for configuration

cmd/heimdalld/main.go, helper/config.go, helper/config_test.go, server/root.go
As part of the deployment of Heimdall in the PoS mainnet. The users have to use the seed/bootnode files defined in the Polygon docs to start the Heimdall process and connect to the network. This is not very UX friendly.
https://docs.polygon.technology/docs/validate/validate/run-validator-ansible/#configure-the-heimdall-service
Since the seed nodes do not change, this issue proposes to hardcode the values of this nodes inside the binary so that the user can run $ heimdall --chain mainnet and connect immediately to the network.
Otherwise, it would require to create a config file, check the docs to get the specific nodes and run Heimdall with that config. Note that this also make it difficult to run in automatic deployments.
Notes:
- If the user supplies other seed nodes either from flags …
=> POS 32 Heimdall add seeds into code for mainnet

Makefile, bridge/cmd/root.go, cmd/heimdallcli/main.go
This PR ensures that the `version` command can be used with all binaries (`heimdalld`, `heimdallcli` and `bridge`).
One issue was that a config file was required in order to run any command (which is now only required when not running the `version` command).
Another issue was that the `BUILD_FLAGS` weren't passed to the `go build` command.
=> Ensure `version` command runs on all binaries

checkpoint/client/rest/query.go
https://heimdall.api.matic.network/checkpoints/latest
and 
https://heimdall.api.matic.network/checkpoints/](https://heimdall.api.matic.network/checkpoints/{ID}
They show heimdall block height = 0
We need to show height correctly as shown here :
https://heimdall.api.matic.network/checkpoints/count
=> Fixed Height Bug 

bridge/setu/broadcaster/broadcaster.go, bridge/setu/listener/rootchain.go, helper/call.go, helper/config.go
This PR adds timeout to the RPC calls happening to main chain and child chain. It adds 2 new config params named EthRPCTimeout and BorRPCTimeout, with default time set to 5 seconds.
Have tested on internal mumbai and mainnet nodes, no breaking changes. 
Linear: [POS 192: Heimdall get receipt context timeout](https://linear.app/matic/issue/POS-192/heimdall-get-receipt-context-timeout)
=> helper, bridge/setu: add context on rpc calls for timeout

helper/config.go
This PR contains a minor fix while printing the default bor rpc timeout.
=> helper: fix typo of displaying bor rpc timeout instead of eth

cmd/heimdalld/testnet.go
Incorrect help info was leading to confusion.
=> Correction to help info for "-n" flag on create-testnet

bridge/setu/processor/base.go, bridge/setu/util/common.go, bridge/setu/util/types.go
This PR adds additional delay by bridge in sending txs to heimdall based on the state of the mempool.
It will increase the delay factor for every 1000 unconfirmed txns in mempool.
For example if the current default delay is 12 Seconds
Then for upto 1000 txns it will stay as 12 sec
For 1000-2000 It will be 24 seconds
For 2000-3000 it will be 36 seconds
Basically for every 1000 txns it will increase the factor by 1.
=> Change TaskDelayBetweenEachVal in bridge based on mempool

bridge/setu/broadcaster/broadcaster_test.go, bridge/setu/processor/base.go, bridge/setu/processor/clerk.go, bridge/setu/processor/fee.go, bridge/setu/processor/processor_test.go, bridge/setu/processor/slashing.go, bridge/setu/processor/staking.go, bridge/setu/util/common.go, bridge/setu/util/types.go
This PR tries to achieve multiple things. 
1. It generalises the `isOldTx` function for all processors by moving it to base processor. 
2. Before broadcasting any state-sync transaction, it will also check with all existing transactions in the mempool through the `checkTxAgainstMempool` function in the base processor for duplicate transaction. This function is kept generic to allow enabling this for other transaction types as well. It will retry the same state-sync transaction post some fixed delay, if a transaction in mempool is found.
Checklist before merging
Linear task
POS-277: [Mempool check for heimdall transactions](https://linear.app/matic/issue/POS-277/mempool-check-for-heimdall-transactions)
=> bridge/setu: check state sync tx against mempool while broadcast

checkpoint/client/cli/query.go, checkpoint/client/rest/query.go
https://linear.app/matic/issue/POS-279/add-checkpoint-id-in-rest-apis-results
=> Add Checkpoint ID in REST APIs Result

.github/workflows/dockerimage.yml, Dockerfile.deprecated, Makefile, docker/start.sh
Restore classic image workflow
Related to https://github.com/maticnetwork/bor/pull/368
=> Bump Go version to v1.18.1

builder/files/heimdalld.service
We need to provide flag `--all` to enable all bridge services. Otherwise the cli will fail
immediately.
=> [Bug fix] Add --all flag to bridge

Dockerfile, docker/entrypoint.sh
Change default heimdall home to `/var/lib/heimdall`. Remove initialization step from entry point since heimdalld is able to initialize configs automatically.
=> Docker changes for v0.3.0

go.sum, helper/call.go, helper/call_test.go
This PR optimise the `helper.NewContractCaller` method. This method has been identified as one of the most consuming during cpu and memory profiling, because of the massive usage of `getABI` function and its underlying json decoding.
By introducing a package level cache map of ABIs, the method will not use json decoding features after the first time `NewContractCaller` has been called, and the map has been initialised.
Unit test has been provided to prove the cache works as expected.
Benchmark results without cache:
```
goos: darwin
goarch: amd64
pkg: github.com/maticnetwork/heimdall/bridge/setu/processor
cpu: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
BenchmarkSendStateSyncedToHeimdall-12    4741   248158 ns/op   49238 B/op   497 allocs/op
BenchmarkIsOldTx-12                     21034 …
```
=> new: dev: pos-620 introduce cache for contracts ABIs

.github/workflows/ci.yml
This change will prevent github workflow from re-running when the description of the PR is edited.
=> Remove 'edit' from github CI workflow

.goreleaser.yml, builder/files/heimdall-post-install.sh, builder/files/heimdalld.service
This change will check and create a new 'heimdall' user when a heimdall binary is installed on a user's machine.
=> Add 'heimdall' user during package installation

integration-tests/smoke_test.sh
Adding more support for Matic-CLI.The integration tests will not give false positives in case default validator balance in Matic-CLI is increased.
=> chg : generalised state-sync integration test

.github/workflows/ci.yml, go.mod, go.sum
This change will bring in the [log tag change](https://github.com/maticnetwork/tendermint/pull/25) in tendermint.
=> Update tendermint version

bor/handler.go, checkpoint/handler.go, checkpoint/handler_test.go, checkpoint/side_handler.go, common/error.go, slashing/handler.go, slashing/side_handler.go
The following misspelling was found in the logs, therefore I tried to fix it.
```
Blocks not in countinuity
```
That should be:
```
Blocks not in continuity
```
However, this value has been changed in the whole source code, including minor functions and error messages.
It's not a serious PR, it can be ignored.
=> Log misspell

.github/workflows/ci.yml, Dockerfile, Dockerfile.release
This PR updates the heimdall working directory to /var/lib/heimdall and runs the docker container as a non-root user (heimdall) as part of the v0.3.0 release. Same as PR #900 but for QA.
=> Update Docker images for v0.3.0 release in QA

Dockerfile, Dockerfile.release
This change rolls back using a heimdall user, reverting to the previous root user due to file path dependencies in matic-cli
=> rollback heimdall user and use root

cmd/heimdalld/service/init.go, cmd/heimdalld/service/service.go, helper/config.go
This commit changes the behavior of heimdalld init command, which will
* not overwrite heimdall-config.toml when the file already exists
* only overwrite genesis.json if flag '--overwrite-genesis' is provided
Do the features included by this PR must be enabled only for a subset of nodes?
In case, please specify how you handled it (e.g. by adding a flag with a default value...)
=> Don't overwrite heimdall-config in heimdalld init

.github/pull_request_template.md
Small correction on the order of the checks in the PR template, as suggested dy @cffls 
Do the features included by this PR must be enabled only for a subset of nodes?
In case, please specify how you handled it (e.g. by adding a flag with a default value...)
=> dev: chg: minor fix to slightly change PR template structure

.github/workflows/security-ci.yml, .github/workflows/security-sonarqube-ci.yml
This PR moves `sonarqube` into its own security ci.
This is use to the fact that our current `sonarqube` version can only run on 1 branch, the default one (`develop` in this case).
Since we want to keep majority of the checks on the PR level, we’ll move `sonarqube` into a separate `yaml` until license will be extended to run on every PR.
=> dev: chg: POS-1215 move sonarqube to own ci

bridge/setu/util/common.go, cmd/heimdalld/service/service.go, helper/config.go, server/root.go
Added a new flag to print logs in a file if required, This will be useful when running bor-heimdall together as a single process after this [PR](https://github.com/maticnetwork/bor/pull/646) is merged. 
=> Added logs_writer flag

.github/workflows/ci.yml, .github/workflows/packager.yml, .github/workflows/release.yml, .golangci.yml, Makefile, go.mod, go.sum
In this PR, we bump go version to `1.20.1`
=> bump : go version to v1.20

bridge/setu/listener/rootchain_events.go, helper/call.go
This PR cherry picks the changes related to `unstakeInit` bug from `master` branch and introduces constant strings for smart contracts' events.
=> dev: chg: POS-1114 & POS-1180: fix unstakeInit bug and introduce constants

scripts/updateVersion.sh
Instead of manually updating the version across all the files, use this script and provide all 4 components of the version, and it will update the version across all 7 files.
```
./scripts/updateVersion.sh 
```
```
The version is of form - VersionMajor.VersionMinor.VersionPatch-VersionMeta
Let's take 0.3.4-beta as an example. Here:
* VersionMajor is - 0
* VersionMinor is - 3
* VersionPatch is - 4
* VersionMeta is  - beta
Now, enter the new version step-by-step below:
* VersionMajor: 0    
* VersionMinor: 3
* VersionPatch: 5
* VersionMeta (optional, press enter if not needed): beta
New version is: 0.3.5-beta
Updating Version Done
```
=> Added a script to increase the version

clerk/client/rest/query.go
Handle `heimdalld not in sync` when bor is querying latest state-syncs for syncing blocks. In request we send 'to-time' timestamp. We return `nothing` if `to-time` > `heimdall_latest_block_timestamp`
=> clerk/client/rest :: add : blocktime check in recordListHandlerFn

gov/client/utils/utils.go, types/validator.go, types/validator_test.go
This PR fixes  the tests `TestParseSubmitProposalFlags`,`TestValidateBasic` and `TestNewValidator`.
=> gov,types: fix tests

cmd/heimdalld/service/service.go
The halt-height and halt-time options are useful to sync the heimdall daemon to a predetermined block height or block time and then exit, allowing state at a given point in time to be reproduced for research and debugging purposes.
The Cosmos SDK which is part of heimdall defines these configuration options and implements them in the BaseApp.
However heimdall does not pass the relevant configuration to NewBaseApp() resulting in these options being ignored; this pull request addresses this.
There is additionally one clean up replacing the use of the literal string "pruning" for retrieving a configuration option the constant flagPruning which is already defined in the source code file and is used elsewhere.
=> Fix HaltHeight and HaltTime config/CLI options so that they work

helper/config.go
This PR fixes`newHexToStringAlgoHeight` block height for Mumbai.
=> helper: change newHexToStringAlgoHeight height for mumbai

slashing/client/cli/tx.go, slashing/client/rest/query.go, slashing/keeper.go, slashing/side_handler.go, staking/client/rest/query.go, staking/genesis.go, staking/keeper.go, staking/keeper_test.go, topup/keeper.go, types/simulation/account.go, types/validator.go
=> Typos on go files

Makefile
Added `make help` feature to display possible targets of the `make` command.
- [] Bugfix (non-breaking change that solves an issue)
```
$ make help 
Available targets:
clean               - Removes the build directory.
tests               - Runs Go tests on specific packages.
build               - Compiles the Heimdall binaries.
install             - Installs the Heimdall binaries.
contracts           - Generates Go bindings for Ethereum contracts.
build-arm           - Compiles the Heimdall binaries for ARM64 architecture.
lint                - Runs the GolangCI-Lint tool on the codebase.
build-docker        - Builds a Docker image for the latest Git tag.
push-docker         - Pushes the Docker image for the latest Git tag.
build-docker-develop- Builds a Docker image for the development …
```
=> Improvements on Makefile

app/app.go, auth/ante.go, auth/ante_test.go, bridge/setu/processor/milestone.go, checkpoint/handler.go, checkpoint/side_milestone_handler.go, checkpoint/side_milestone_handler_test.go, helper/config.go, staking/keeper.go
This PR merges all the following hf
1.GetValidatorSetRotationStopHeight
2.GetMilestoneHardForkHeight()
3.GetNoAckProposerCheckHeight()
into the one single aalborg hf
=> Combine multiple hardforks into one

checkpoint/side_handler.go, checkpoint/side_handler_test.go
This PR fixes condition for `checkpoint-ack` transaction in post-handler.
=> checkpoint: Fix checkpoint ack condition

auth/ante.go, auth/ante_test.go
This PR includes the fix for the error which is returned when the milestone transaction 
get included in the block before the hardfork block
=> auth: update error type when milestone tx arrives before HF

.github/workflows/ci.yml
This PR increases the timeout for smoke tests to 60 minutes in the CI workflow.
=> CI: increase smoke test timeout

helper/call.go
This PR adds the check in receipt calculation to account for finalized tag in main chain (eth). This change was mistakenly removed in the milestone's PR.
=> helper: use finalized for receipt calculation

bor/README.md
This PR adds a `README` for `bor` module.
=> Add README for bor module

helper/query.go
This is a minimal fix for issue #1026 affecting only heimdall and not the underlying tendermint/peppermint.
ValidateTxResult() is modified such that where the merkle proof fails verification, if the transaction is the only transaction block and the block header root hash matches the hash of the transaction, the transaction is considered valid.
Any node running the heimdall rest server or the heimdall CLI tool.
Run `heimdallcli query tx --chain-id=heimdall-137 [TXID]` and similar queries - ensure transactions from single transaction blocks are reported as valid.
=> ValidateTxResult: accept single transaction blocks as currently produced by heimdall as valid

checkpoint/client/rest/query_milestone.go, helper/config.go
This PR reverts the calls related to the upcoming `Aalborg` hard fork with status code 503 until the hard fork block number kicks in. This is to notify bor about whether the HF has kicked in or not. 
=> checkpoint/client: revert with 503 status code until HF

staking/README.md, staking/client/cli/query.go, staking/client/cli/tx.go
This PR adds README for `staking` module and fixes a few typos.
=> Add staking module README

.github/workflows/codeql.yml
Install `go` as part of the CodeQL workflow by using the version taken from `go.mod`
=> install go in CodeQL workflow

bor/README.md
This PR refactors `Query commands` section in `bor` module README for consistency with those of other modules.
=> Restructure query command section in bor

cmd/heimdalld/service/service.go
The log of `Heimdall services stopped` was in a wrong place where it printed this log where any `heimdalld` sub-command (e.g., `version`, `init`) has called.
Following we test the `version` sub-command. 
```
/usr/bin/heimdalld version
1.0.1
INFO [2023-10-02|14:09:17.940] Heimdall services stopped                    module=cmd/heimdalld
```
```
/usr/bin/heimdalld version
1.0.1
```
The same would apply to all other sub-commands.
=> fix: log/service stopped

bank/README.md
=> add bank readme

supply/README.md
This PR provides the readme for supply module and how to use it.
=> Supply module readme

helper/unpack.go, packaging/deb/heimdalld/DEBIAN/control, packaging/templates/package_scripts/control, packaging/templates/package_scripts/control.arm64, packaging/templates/package_scripts/control.profile.amd64, packaging/templates/package_scripts/control.profile.arm64, packaging/templates/package_scripts/control.validator, packaging/templates/package_scripts/control.validator.arm64, staking/side_handler_test.go
PR to merge `v1.0.3-candidate` to `master`.
=> Merge V1.0.3 candidate to master

go.mod, go.sum
maticnetwork/tendermint v0.33.1 changes a few error logs as debug logs, and also added an extra log to get information about the number of peers.
=> Update Tendermint version to v0.33.1

bridge/README.md
=> Added Bridge README

.github/workflows/packager.yml, packaging/templates/package_scripts/postinst.profile.amoy
-  add amoy testnet packaging  workflow entries
- [X ] New feature (non-breaking change that adds functionality)
=> add amoy testnet deployment entries

server/README.md
=> Server README

bridge/README.md
Merge master to develop (post conflict resolve).
=> Merge master to develop

bridge/cmd/start.go, client/tx/query.go, cmd/heimdallcli/main.go, cmd/heimdalld/service/init.go, cmd/heimdalld/service/rollback.go, cmd/heimdalld/service/service.go, cmd/heimdalld/service/testnet.go, gov/client/cli/query.go, gov/client/cli/tx.go
Nothing fancy, just a clean up of some flags description.
=> chore: enforce capitalisation in flags description

integration-tests/bor_health.sh, integration-tests/smoke_test.sh
Based on `matic-cli` [PR](https://github.com/maticnetwork/matic-cli/pull/225), this adapts the path accordingly also in `heimdall` integration tests
- In case link the PR here: https://github.com/maticnetwork/bor/pull/1173
- In case link the PR here: https://github.com/maticnetwork/matic-cli/pull/225
=> Fix path for `matic-cli` dockerized tests

.github/workflows/ci.yml, integration-tests/fund_ganache_accounts.sh
Often, the checkpoints submission during the `e2e tests` in the CI takes a very long time (35+ mins) due to lack of funds in ganache accounts (with `index > 0`), which ends up in checkpoints submission failure, and subsequent rotation until it's `accounts[0]` turn. 
This PR introduces a new script to fund the ganache accounts right before the `e2e tests`, to reduce the checkpoint submission time from 35+ mins to around 2 mins.
=> POS-2399: ganache bug workaround to reduce `smoke_test` time in CI

bridge/setu/listener/rootchain_log.go, bridge/setu/util/common.go, helper/tx.go, staking/client/cli/tx.go, staking/side_handler.go, staking/side_handler_test.go, staking/simulation/utils.go
This PR fixes a bug in `staking` module.
Valid for all nodes, required for validators.
=> bridge, staking: chg: bug fix

checkpoint/keeper.go
The max limit of checkpoint/list api is set to 20 which is very small. E.g. https://heimdall-api.polygon.technology/checkpoints/list?page=1&limit=10000 returns only 20 instead of 10,000.
Checkpoint objects are very small ~100 bytes each. We can fit ~ 10,000 in a 1 MB response size. Feels like this should not be something that can affect the process badly.
Context: Erigon would like to efficiently fetch checkpoints from heimdall for an improved initial sync mechanism. We would like to batch fetch efficiently hence the change.
- In case link …
=> checkpoint: list api increase max limit

app/test_helpers.go, bridge/setu/broadcaster/broadcaster.go, bridge/setu/broadcaster/broadcaster_test.go, bridge/setu/processor/checkpoint.go, bridge/setu/processor/clerk.go, bridge/setu/processor/fee.go, bridge/setu/processor/milestone.go, bridge/setu/processor/processor_test.go, bridge/setu/processor/slashing.go, bridge/setu/processor/span.go, bridge/setu/processor/staking.go, helper/config.go, helper/test_helpers.go, helper/util.go
The job of the `broadcaster` component is, as the name suggests, to broadcast txs to tendermint. The ante handler is executed during `checkTx` (invoked by tendermint) and enforces some sanity checks on the tx sent (ensuring enough balance, correct signature, etc.) and at successful verification, increments the account sequence (akin to nonce). 
If any of the checks were to fail, the appropriate error code is baked in `sdk.TxResponse`.
Currently, the `broadcaster` doesn't account for a failed sanity clause (and only checks for errors that pop up _during_ the broadcast itself). This results in an incorrect increment of the bridge's "cached" account sequence and hence causes mismatch with the DB. This PR aims to fix this.
=> Handle account sequence correctly in bridge

bor/keeper.go
The max limit of spans/list api is set to 20 which is very small. Currently each span is around 6 KB, we can fit ~160 in a 1 MB response size. This PR sets the limit to 150 to account for future span size growth. 
Context: Erigon would like to efficiently fetch spans from heimdall for an improved initial sync mechanism. We would like to batch fetch spans cut down the number of requests sent to the heimdall service.
```
➜  ~ curl 'http://localhost:1317/bor/span/list?page=1&limit=10' | jq | grep "span_id" | wc -l
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  132k    0  132k    0     0   173k      0 --:--:-- --:--:-- --:--:--  173k
10
➜  ~ curl …
```
=> bor: increase max limit for list span api

checkpoint/client/rest/query.go, checkpoint/keeper.go, checkpoint/keeper_test.go, types/header.go
Return checkpoint IDs in `checkpoints/list` similar to `checkpoint/{number}`. In Erigon at the moment, we have to infer the checkpoint ID by checking its index in a sorted list of checkpoints. Returning the checkpoint ID will let us rely on Heimdall's IDs and reduce the chance of any discrepancies.
```
curl -s http://localhost:1317/checkpoints/list\?page\=1\&limit\=5 | jq
{
"height": "4449411",
"result": [
{
"id": 1,
"proposer": "0x6ab3d36c46ecfb9b9c0bd51cb1c3da5a2c81cea6",
"start_block": 0,
"end_block": 114,
"root_hash": "0x767b9ed2c10b2aaf7d39df9a1142b9de3a4e246db5c28fe2697ed2e92cf4a061",
"bor_chain_id": "80002",
"timestamp": 1700396194
},
{
"id": 10,
"proposer": "0x6ab3d36c46ecfb9b9c0bd51cb1c3da5a2c81cea6",
"start_block": 4979, …
```
=> Return checkpoint IDs in `checkpoints/list`

.github/workflows/packager_deb.yml
=> chg: bump go in packager deb

clerk/keeper.go, clerk/module.go, cmd/heimdallcli/main.go, cmd/heimdallcli/main_test.go, cmd/heimdallcli/testdata/dump-genesis.json, types/module/module.go
Optimization of export genesis command to use less memory.
=> Optimization of export genesis command

bridge/setu/listener/rootchain_selfheal_graph.go, bridge/setu/processor/base.go, bridge/setu/util/common.go, helper/call.go, helper/util.go, types/rest/rest.go
In this PR we provide a bytes limit for the heimdall API responses.
Also, we fix a NPE during smart contracts' calls.
=> Limit bytes during response body read / NPE fix

bridge/setu/util/db.go
Currently, the `GetBridgeDBInstance` function does not handle scenarios where `bridgeDB` may be nil. If the database fails to open for any reason, returning a nil object can lead to potential runtime panics or errors when the returned database instance is used. Adding error handling will help prevent these issues and improve the robustness of the code.
- Added error handling within the `sync.Once` block to capture and return any errors encountered while opening the LevelDB database.
Before:
```go
func GetBridgeDBInstance(filePath string) *leveldb.DB {
bridgeDBOnce.Do(func() {
bridgeDB, _ = leveldb.OpenFile(filePath, nil)
})
return bridgeDB
}
```
After:
```go
func GetBridgeDBInstance(filePath string) *leveldb.DB {
bridgeDBOnce.Do(func() {
var err error
bridgeDB, err = …
```
=> Enhance GetBridgeDBInstance: Add Error Handling for LevelDB Initialization

helper/config.go
Fixes the `DefaultBorGRPCUrl`, just for clarity, since it would work anyway considered the `removePrefix` function.
=> Fix DefaultBorGRPCUrl

bor/client/grpc/grpc_util_test.go
This PR fixes a `gRPC` which is failing due to the switch from decimal to `hex` encoding/decoding.
=> Fix gRPC test due to new hencoding

bor/client/cli/query.go, bor/client/cli/tx.go, bor/client/rest/tx.go, bor/handler.go, bor/keeper.go, bor/keeper_test.go, bor/querier.go, bor/side_handler.go, bor/types/codec.go, bor/types/msg.go, bor/types/querier.go, bridge/setu/processor/span.go, cmd/heimdalld/service/service.go, helper/config.go
Added new msg for proposing span `MsgProposeSpanV2` that doesn't do external calls to `bor` in `PostHandleMsgSpan`.
=> V1.1.0 new span msg

bridge/setu/util/common.go
fix some function names in comment
It is a new pr for https://github.com/maticnetwork/heimdall/pull/1178 but against develop.
=> chore: fix some function names in comment

go.mod
Cosmos SDK reported a [High Severity Vulnerability on version 0.50.6](https://github.com/advisories/GHSA-x5vx-95h7-rv4p), so this change is aiming upgrade to a patched version.
=> Patch Cosmos SDK v0.50.6 -> v0.50.12

.github/pull_request_template.md, README.md
Removes usage of Mumbai from README and backports `master` branch.
=> chore: Remove usage of Mumbai from README

cmd/heimdallcli/main.go, cmd/heimdallcli/main_test.go
Fix the genesis export command by making it deterministic.
=> make genesis export deterministic

bridge/setu/listener/rootchain_log.go, bridge/setu/processor/checkpoint.go, checkpoint/handler.go, checkpoint/side_handler.go, cmd/heimdalld/service/service.go, common/error.go, helper/config.go, simulation/simulate.go
This PR attempts to halt checkpoint submission 300 blocks prior to the apocalypse HF.
=> Prevent checkpoint submission prior to the apocalypse

helper/config.go
Heimdall will stop at height 8788500. This is supposed to be used for the Amoy Heimdall migration.
=> helper: set the  apocalypseHeight to 8788500 (to use for amoy only)
