- bridge/pier/checkpoint.go
- bridge/pier/clerk.go
- bridge/pier/common.go
- bridge/pier/syncer.go
This PR contains
- Bug fixes in syncer
- Stake Events Sender selection.
> Bridge fixes

- bridge/pier/ack.go
- bridge/pier/checkpoint.go
- checkpoint/cli/tx.go
- checkpoint/handler.go
- checkpoint/handler_test.go
- checkpoint/msg.go
- checkpoint/rest/tx.go
- test/common.go
> Deffering to UTC time for all transactions WIP

- app/app.go
- bank/handler.go
- bank/keeper.go
- bank/types/topup.go
- staking/handler.go
- staking/keeper.go
> Use topup and staking sequence 

- auth/module.go
- auth/types/genesis.go
> fix bug #124

- bor/client/rest/query.go
- bor/keeper.go
> Sort validators before adding to span 

- bor/querier.go
- bridge/pier/common.go
- bridge/pier/span.go
> handle first span in querier

- checkpoint/handler.go
- common/error.go
> Remove min balance check

- bor/client/cli/tx.go
- bor/client/rest/tx.go
> fixed encoding error

- helper/call.go
- staking/client/cli/tx.go
- staking/handler.go
Fix invalid log index while sending validator join tx and use event log instead of contract state for validator join
> Fixes #207 and #208

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- helper/toml.go
Adds issue and PR templates to get all the data we need from users.
> Add issue and PR templates

- monitoring/dashboard.json
- monitoring/datasource.json
- monitoring/heimdall_monitoring.sh
> Enabled Prometheus for Heimdall

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> Adds PR and issue templates

- .github/workflows/dockerimage.yml
CI for Docker push to DockerHub
> added docker push github actions workflow

- bridge/setu/listener/heimdall.go
- bridge/setu/listener/rootchain.go
- bridge/setu/processor/checkpoint.go
- bridge/setu/processor/clerk.go
- helper/tx.go
1. Remove `Restake` task. Since `StakeUpdate` is correct task
2. Remove signer udpate tx from other validators. Only current signer can update it
3. Add topup fee tx: if utils.isEventSender else delay for `topupFee`, similar to StakeUpdate
4. Fix gas limit issue for Bor transactions. Only checkpoint should have 5m limit
Also fixed below issue
Estimate gas failing for 2 reasons
1. Proxy contract requires 5million gas. ( intermittently). 
2. revert from contract due to stake mismatch.
Solution
1. send checkpoint tx with 5million gas. [resolves proxy contract issue]
2. if stake mismatch happens, try for other set of transactions sent to heimdall with same startblock and endblock.
> Gas limit error. Testing In progress

- bridge/setu/listener/rootchain.go
- cmd/heimdallcli/stake.go
- helper/tx.go
Fixes the following issues:
* use public key without prefix
* use chainmanager params API for stake cli commands
> Fix: public key usage and stake cli commands

- types/validator.go
- types/validator_test.go
adding unit tests for type validator. simply adding expected cases and outcomes by reviewing the code
> Validator unit tests

- app/app.go
- app/app_test.go
- app/config.go
- app/sim_test.go
- staking/module.go
- staking/simulation/genesis.go
Package: app
coverage: 49.1% of statements
> mat-1121 add simulation for staking module

- docker/start.sh
Add sleep 100s which is enough for heimdall to start.
> Wait for heimdall to start

- bridge/setu/processor/slashing.go
- slashing/msg_test.go
- slashing/slashinfo_test.go
- slashing/types/infohash.go
Covert slashed amount into decimals when submitted to contracts
> MAT-1446 - Fix power conversion

- slashing/handler.go
Tick should be submitted to heimdall even if slash-limit is not exceeded.
> MAT-1449 - Remove slash limit

- clerk/client/rest/query.go
- clerk/genesis.go
- clerk/keeper.go
- clerk/querier.go
- clerk/side_handler.go
- clerk/side_handler_test.go
- clerk/types/querier.go
- common/error.go
Clerk deposit txs should be processed sequentially on heimdall.
> MAT-1464 - Clerk sequential tx

- clerk/client/rest/query.go
- clerk/genesis.go
- clerk/keeper.go
- clerk/querier.go
- clerk/side_handler.go
- clerk/side_handler_test.go
- clerk/types/querier.go
- common/error.go
Reverts maticnetwork/heimdall#364
> Revert "MAT-1464 - Clerk sequential tx"

- bridge/setu/listener/rootchain.go
- bridge/setu/processor/checkpoint.go
> fix: check if event checkpoint is older/equal to latest checkpoint

- cmd/heimdalld/cmd/genaccounts.go
- cmd/heimdalld/cmd/root.go
- x/auth/types/account.go
- x/chainmanager/module.go
- x/checkpoint/module.go
- x/gov/module.go
- x/topup/module.go
Fixed grpc methods 
Fixed build issues
> fixed grpc methods

- cmd/heimdalld/cmd/init.go
- cmd/heimdalld/cmd/root.go
#428 
Added overwrite flag for init command.
> add overwrite flag for init command. ref#428

- make/release.mk
Fixes issues with `make build` and `make heimdall`.
> Fix make cmds

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/proto.yml
- .github/workflows/release.yml
- .github/workflows/stale.yml
- .github/workflows/test.yml
- Makefile
- make/lint.mk
- make/test.mk
> Add dependabot, lint, proto, release, stale, test CI checks

- scripts/protoc-gen.sh
> add grpc-gateway file generate command 

- app/app.go
- app/side_tx_processor_test.go
- cmd/heimdalld/cmd/init.go
- cmd/heimdalld/cmd/root.go
- file/perm_check.go
- types/bytes.go
- types/common/pubkey.go
- types/dividend-account.go
- types/rest/rest.go
- types/validator-set.go
- x/chainmanager/client/rest/rest.go
- x/checkpoint/client/rest/rest.go
- x/gov/client/rest/rest.go
- x/sidechannel/client/rest/rest.go
- x/sidechannel/keeper/keeper.go
- x/sidechannel/module.go
- x/staking/client/rest/rest.go
- x/staking/keeper/keeper.go
- x/topup/client/rest/rest.go
I will be raising multiple PRs for fixing different linter errors. This is the first one (from gosimple linter).
> fixing gosimple linter errors

- app/app.go
- app/encoding.go
> fix init error

- proto/heimdall/clerk/v1beta1/msg.proto
- proto/heimdall/staking/v1beta1/query.proto
- x/staking/side_handler.go
- x/staking/side_handler_test.go
> fix the signer checking while validation-join

- helper/call.go
- x/staking/client/cli/tx.go
> chg: remove unwanted code

- x/clerk/client/cli/query.go
- x/clerk/client/cli/tx.go
> chg: use event to parse data instead of passing through flags

- cmd/heimdalld/cmd/init.go
> fix the genesis data initialization

- x/checkpoint/client/cli/tx.go
> added CheckpointACKTxCmd to tx cli of checkpoint

- x/checkpoint/client/cli/query.go
> added missing cli queries to checkpoint

- x/checkpoint/types/msg.go
- x/topup/types/msg.go
> fix the signer pubkey match issue in topup

- checkpoint/handler_test.go
- checkpoint/side_handler.go
- checkpoint/side_handler_test.go
- checkpoint/types/merkel.go
Min Confirmations check on every node for checkpoints.
> Add min bor block confirmation check

- .goreleaser.yml
- Makefile
- builder/files/heimdalld.service
Already included in main binary
> Do not build or run bridge

- checkpoint/client/cli/query.go
Fixed : https://linear.app/matic/issue/POS-177/heimdallcli-query-checkpoint-bug
> fixed: cli-checkpoint-count

- scripts/json2wal/main.go
- scripts/wal2json/main.go
POS-176 
Added tendermint scripts to heimdall to solve the wal corruption error.
> Added json2wal and wal2json scripts

- Makefile
- mumbai.toml
> mumbai upgrade for v0.2.8

- bridge/setu/util/common.go
Conclusion of the analysis about RFC-49
> fix: dev: pos-463 set TaskDelayBetweenEachVal to 10s

- README.md
I noticed these backticks were missing.
> Add missing backticks

- Makefile
This PR uses build flags in go build command. This will fix the issues with version command. 
> Makefile: use build flags in go build

- .github/pull_request_template.md
This PR updates the PR template to include an additional check for node audience, to ensure higher attention in case of features which must be enabled only for a subset of nodes.
> dev: chg: update PR template to include nodes audience check

- Makefile
This change will force run all unit tests in a single thread. This is a temp fix to the failures caused by multiple tests are trying to register GenesisAccount type at the same time for the global codec variable: https://github.com/maticnetwork/heimdall/blob/e26a9a891829f0ce84843b3801019c29f91197e9/auth/types/codec.go#L19.
A long-term fix is to remove the need of module variable ModuleCdc in auth/types/codec.go.
Do the features included by this PR must be enabled only for a subset of nodes?
In case, please specify how you handled it (e.g. by adding a flag with a default value...)
Please complete this section with the steps you performed if you …
> Run unit tests in single core

- helper/config.go
Hi Guys, I am creating this PR to remove an unused piece of code which is creating a cyclic dependency and creating issue with some work on bor project.
Do the features included by this PR must be enabled only for a subset of nodes?
In case, please specify how you handled it (e.g. by adding a flag with a default value...)
> Remove unwanted import as it is creating cyclic dependency

- .github/matic-cli-config.yml
- .github/workflows/ci.yml
- integration-tests/bor_health.sh
- integration-tests/smoke_test.sh
This PR updates matic-cli branch used in CI integration tests to master and also makes subsequent modifications to matic-cli-config.yml
> CI: update CI to use matic-cli master branch

- packaging/deb/heimdalld/DEBIAN/control
- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
Bump heimdall version to v0.3.2
> packaging: bump version

- go.mod
- go.sum
Bump dependency for crypto package
> dev: chg: bump crypto package

- .github/workflows/security-ci.yml
- .github/workflows/security-sonarqube-ci.yml
- README.md
- bridge/setu/util/common.go
- cmd/heimdalld/service/init.go
- cmd/heimdalld/service/service.go
- go.mod
- go.sum
- helper/config.go
- helper/toml.go
- server/root.go
This PR merges `develop` to `qa`
> Merge develop to qa

- .github/workflows/security-ci.yml
- app/side_tx_processor.go
- auth/ante.go
- auth/types/account_retriever.go
- bor/shuffle.go
- chainmanager/genesis_test.go
- checkpoint/module.go
- clerk/genesis_test.go
- clerk/side_handler_test.go
- helper/config_test.go
- sidechannel/genesis_test.go
- simulation/doc.go
- simulation/log.go
- simulation/util.go
- staking/types/msg.go
- topup/genesis_test.go
- types/dividend-account.go
- types/side_msg.go
- types/validator-set.go
- version/version.go
Given the GH license changes and `snyk` integration, we are not throwing errors when `snyk` report upload to GH fails
> dev: chg: continue on error when uploading snyk results to GH

- .github/workflows/release.yml
- Makefile
This PR adds login to docker hub for release workflow
> dev: add: add login to docker hub for release workflow

- .github/workflows/packager.yml
- [ x] Hotfix (change that solves an urgent issue, and requires immediate attention)
Added use of 18.04 self hosted runner as currently the Github hosted 18.04 has been end of life.
> Adding self hosted 18.04 runner usage

- clerk/client/rest/query.go
> Added logs to event-record handler

- .github/matic-cli-config.yml
Change `contracts` branch for the ci to use node-16.
> dev: chg: use node-16 contracts branch

- app/app.go
- helper/config.go
- helper/config_test.go
This change allows us to change root chain contract addresses in heimdall if we want to migrate root chain contract from a chain to another.
> Enable migration of root chain contract addresses

- .github/matic-cli-config.yml
This PR updates the yaml config file to bootstrap devnet for CI.
> ci: update CI yaml config

- bridge/setu/processor/slashing.go
- bridge/setu/processor/staking.go
> bridge: update code comment

- packaging/deb/heimdalld/DEBIAN/control
- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
> version bump to v0.3.4

- helper/call.go
> helper: return error in client call to fetch root hash

- helper/config.go
Improve logging to prevent misleading users when using default config values. 
> helper: improve logging for default config values

- bridge/setu/processor/slashing.go
- bridge/setu/processor/staking.go
> Update code comments

- app/app.go
- app/params/doc.go
- app/side_tx_processor_test.go
- app/types.go
- auth/ante_test.go
- bor/types/bor.go
- bridge/cmd/root.go
- bridge/setu/listener/base.go
- bridge/setu/processor/service.go
- bridge/setu/processor/slashing.go
- checkpoint/client/rest/query.go
- checkpoint/doc.go
- checkpoint/module.go
- clerk/keeper.go
- file/perm_check_test.go
- helper/call.go
- helper/config.go
- server/README.md
Fixed typos in several go files
> fixed typo in multiple go files

- .github/workflows/stale.yml
> exempt draft PRs

- .github/workflows/packager.yml
EOL support for ubuntu 18.04, all builds going forward are for 20.04 and newer compatibility.
- [ x] Bugfix (non-breaking change that solves an issue)
> EOL 18.04 Support

- app/types.go
- checkpoint/client/rest/query_milestone.go
- checkpoint/keeper_milestone.go
- simulation/mock_tendermint.go
- slashing/keeper.go
> Text corrections on go files

- go.mod
- go.sum
- staking/querier.go
Issue: [#1771](https://polygon.atlassian.net/browse/POS-1771?atlOrigin=eyJpIjoiMjg3YzdhNTZjMGU5NDUyM2JjYWM4NTBmZjE5OTk0NWMiLCJwIjoiaiJ9)
- In case link the PR here: [PR#27](https://github.com/maticnetwork/tendermint/pull/27)
Update go.mod once the changes in Tendermint are merged
> staking: update log level

- helper/call.go
Without timeout heimdall chain gets stuck if the RPC server of bor/erigon crashes
> helper:add timeout to getBlockByNumber

- packaging/templates/package_scripts/postrm
- packaging/templates/package_scripts/postrm.binary
- packaging/templates/systemd/heimdalld-mainnet-validator.service
- packaging/templates/systemd/heimdalld-validator.service
Fixes for some postrm to work properly.
Removed entries in service file to require after bor.
> Addressing packages issues

- chainmanager/README.md
Add readme for chainmanager module
> add chainmanager readme

- topup/README.md
Add a README page to topup module.
> Add topup/README.md

- auth/README.md
Used https://wiki.polygon.technology/docs/pos/design/heimdall/modules/auth/ to add README for auth module.
> Added auth Readme

- auth/README.md
- gov/README.md
Added Gov README based on https://wiki.polygon.technology/docs/pos/design/heimdall/modules/governance/
> Gov README

- .github/workflows/ci.yml
This PR updates `matic-cli` according to the changes made in [this PR](https://github.com/maticnetwork/matic-cli/pull/212)
> Update matic-cli in CI

- params/README.md
> Added param README

- .github/matic-cli-config.yml
- integration-tests/bor_health.sh
- integration-tests/smoke_test.sh
Update bor ipc path based on new director structure
> integration-tests: update ipc path on ci tests

- app/app.go
- app/utils.go
- auth/types/stdtx.go
- bor/README.md
- bor/querier.go
- checkpoint/handler.go
- checkpoint/side_handler.go
- checkpoint/types/merkel_milestone.go
- client/tx/broadcast.go
- common/error.go
- params/subspace/subspace.go
- server/README.md
- sidechannel/keeper.go
- simulation/log.go
- simulation/simulate.go
- types/rest/rest.go
Another attempt at https://github.com/maticnetwork/heimdall/pull/1130
> fix: fix typos

- integration-tests/bor_health.sh
- integration-tests/smoke_test.sh
Porting changes from https://github.com/maticnetwork/heimdall/pull/1139 to `master` branch to fix the CI.
> fix: root folder for docker integration tests (#1139)

- packaging/deb/heimdalld/DEBIAN/control
- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
> Bump version to v1.0.5

- go.mod
- go.sum
Updates tendermint version to latest release
> update: tendermint version

- types/rest/rest.go
- types/validator-set.go
> chore: remove repetitive words in comments

- checkpoint/handler_milestone_test.go
- checkpoint/side_milestone_handler.go
- checkpoint/side_milestone_handler_test.go
- checkpoint/simulation/header_milestone.go
- checkpoint/types/merkel_milestone.go
- checkpoint/types/msg_milestone.go
- packaging/deb/heimdalld/DEBIAN/control
- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
Backporting changes from `master` to `develop` after `v1.0.6` release.
> Backport master to develop

- .github/workflows/ci.yml
- .github/workflows/govuln.yml
Update the versions for `actions/download-artifact` and `actions/upload-artifact` due to deprecations.
> Update artifacts upload/download actions version

- bridge/setu/listener/rootchain_selfheal.go
This PR fixes a bug in the selfheal retry logic.
> bridge: selfheal bugfix for statusCheck condition

- .github/workflows/amoy_deb_profiles.yml
- .github/workflows/mainnet_deb_profiles.yml
- packaging/deb/heimdalld/DEBIAN/prerm
- packaging/templates/package_scripts/postinst.validator
- packaging/templates/package_scripts/postrm.profile
Updates to packager to fix file copy to correct profile
Updated prerm to prevent a failure
Updated postrm.profile
- [x ] Bugfix (non-breaking change that solves an issue)
> Profile and packaging fixes

- .github/workflows/ci.yml
Uses the `docker_devnet.sh` script instead of single ones.
If this PR includes changes that must be applied only to a subset of nodes, please specify how you handled it (e.g. by adding a flag with a default value...)
> Simplify e2e-tests CI by using the consolidated script

- supply/types/account.go
- supply/types/permissions.go
This is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
The new pr for https://github.com/maticnetwork/heimdall/pull/1234.
> refactor: using slices.Contains to simplify the code

- checkpoint/keeper_milestone.go
- clerk/types/errors.go
fix wrong function name in go docs
> chore: fix wrong function name in go docs

- cmd/heimdalld/main.go
- version/version.go
> feat: `heimdalld_info` metric

- helper/call.go
Adds a `nil` check on two specific contract calls for `RootChain` contract.
> additional check on contracts call

- .github/workflows/amoy_deb_profiles.yml
- .github/workflows/mainnet_deb_profiles.yml
- .github/workflows/packager_deb.yml
Updated packager to use make_latest: false, instead of prerelease: true for releasing artifacts
Updated packagers to use commit pinned versions of other actions 
- [x ] Bugfix (non-breaking change that solves an issue)
> Packager updates

- checkpoint/genesis.go
- checkpoint/genesis_test.go
- checkpoint/integration_test.go
- checkpoint/keeper.go
- checkpoint/keeper_milestone.go
- checkpoint/simulation/genesis.go
- checkpoint/types/genesis.go
- types/header.go
Added logic to export milestones
> Export milestones

- .goreleaser.yml
- Dockerfile.release
- builder/files/genesis-amoy-v1.json
> amoy genesis file

- bor/handler.go
- bor/side_handler.go
- bor/types/params.go
- bridge/setu/processor/span.go
- go.mod
- go.sum
- helper/config.go
- helper/util.go
- server/gRPC/gRPC.go
- server/gRPC/span.go
Edge cases for span proposition when bor is running without heimdall.
> Bor without heimdall
